[package]
name = "prototool"
description = "Tool zum automatischen generieren von Protokollen und Website Posts"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
askama = "0.12.1"
chrono = { version = "0.4.35", features = ["serde"] }
clap = { version = "4.5.3", features = ["derive", "env"] }
opener = "0.7.0"
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
reqwest = { version = "0.12.2", features = ["blocking", "json", "rustls-tls", "http2", "macos-system-configuration", "charset"], default-features = false }
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
tempfile = "3.10.1"
url = "2.5.0"
uuid = { version = "1.8.0", features = ["v4", "serde"] }
arboard = {version = "3.4.0", features = ["windows-sys", "wayland-data-control"], default-features = false }
libc = "0.2.155"
rustix = {version = "0.38.34", features = ["stdio"], default-features = false  }


[dev-dependencies]
pretty_assertions = "1.4.0"
