[package]
name = "prototool"
description = "Tool zum automatischen generieren von Protokollen und Website Posts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive", "env"] }
anyhow = "1.0.81"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
askama = "0.12.1"
tempfile = "3.10.1"
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
chrono = "0.4.35"
reqwest = { version = "0.12.2", features = ["blocking", "json"] }
url = "2.5.0"
uuid = { version = "1.8.0", features = ["v4", "serde"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
