name: Push to Attic

on: [push]

jobs:
  push:
    name: push ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: true
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: prototool-linux-amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bin: prototool-linux-aarch64

          - os: macos-latest
            target: x86_64-apple-darwin
            bin: prototool-darwin-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            bin: prototool-darwin-aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix develop -c attic login fscs https://attic.hhu-fscs.de ${{ secrets.ATTIC_TOKEN }} 
      - run: nix build
      - run: nix develop -c attic push fscs result 
