name: Push to Attic

on: [push]

jobs:
  push:
    name: upload ${{ matrix.platform.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - target: "x86_64-linux"
          - target: "aarch64-linux"
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix develop .#attic -c attic login fscs https://attic.hhu-fscs.de ${{ secrets.ATTIC_TOKEN }} 
      - run: nix build .#cross-${{ matrix.platform.target }}
      - run: nix develop .#attic -c attic push fscs-public result 
